FROM node:18 AS builder

EXPOSE 80

WORKDIR /app

ARG VITE_THE_GUARDIAN_API_KEY
ARG VITE_NEW_YORK_TIMES_API_KEY
ARG VITE_NEWSAPI_API_KEY
ARG VITE_THE_GUARDIAN_BASE_URL
ARG VITE_NEW_YORK_TIMES_BASE_URL
ARG VITE_NYT_ASSET_CDN_BASE_URL
ARG VITE_NEWSAPI_BASE_URL

ENV VITE_THE_GUARDIAN_API_KEY=$VITE_THE_GUARDIAN_API_KEY
ENV VITE_NEW_YORK_TIMES_API_KEY=$VITE_NEW_YORK_TIMES_API_KEY
ENV VITE_NEWSAPI_API_KEY=$VITE_NEWSAPI_API_KEY
ENV VITE_THE_GUARDIAN_BASE_URL=$VITE_THE_GUARDIAN_BASE_URL
ENV VITE_NEW_YORK_TIMES_BASE_URL=$VITE_NEW_YORK_TIMES_BASE_URL
ENV VITE_NYT_ASSET_CDN_BASE_URL=$VITE_NYT_ASSET_CDN_BASE_URL
ENV VITE_NEWSAPI_BASE_URL=$VITE_NEWSAPI_BASE_URL

COPY package.json package-lock.json ./

RUN npm install 

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
